ChatGPT:
  # opennAI接口地址
  chartGPTUrl: https://api.openai.com/v1/chat/completions
  variables:
    # API KEY 已经废弃 新方式从数据库读取
    apiKey: 填写你自己的apiKey
    # ChartGPT 模型
    model: gpt-3.5-turbo
    # chartGPT随机参数
    temperature: 0.5
    contentType: application/json
    role: user
    #当前接口支持的上下文长度
    contextLength: 36
  #需要被过滤替换的字符串
  Stringfilter: OpenAI|ChartGPT|chartGPT|GPT|
  #apiKey个数
  apiKeyCount: 7

#微信小程序登录工具配置
WeChartLoginTool:
  userinfoUrl: http://00:8888/GPTAuthLogin/user/userinfo

spring:
  #数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: 00
    password: 000..
    url: jdbc:mysql://00:3306/000?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai

  #redis配置
  redis:
    host: 0000
    database: 0
    port: 6379
    password: 000..
    jedis:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
    timeout: 20000ms
